Fixed Naming/MethodParameterName cop name.
Resolves the following error:

    Error: The `Naming/UncommunicativeMethodParamName` cop has been
    renamed to `Naming/MethodParameterName`.